### ISSUE TITLE
TZ not updating

### ISSUE THREAD

**Issue by anujdatar** [anujdatar/duckdns-docker#3]
TZ changes not set up at all, refer to #1 

i never set that up. should add

**Comment by corasaniti** [comment]
you have to add this in Dockerfile
`pk add tzdata`

https://cduser.com/pique-22-how-to-change-timezone-in-a-linux-alpine-container/
Thanks

**Comment by anujdatar** [comment]
TZ support added in the latest release: 23.06.24.

IP address in logs, webhook, IPv6 support coming shortly.
